export const translations = {
  ko: {
    title: '말레이시아 AI 챗봇 어드민',
    systemOnline: 'System Online',
    admin: '관리자',
    dashboard: '대시보드',
    userManagement: '테스트 목록',
    activeChats: '활성화된 대화',
    settings: '설정',
    activeChatCount: '개의 활성화된 채팅',
    selectConversation: '대화를 선택해주세요',
    selectConversationDesc: '왼쪽에서 대화를 선택하면 채팅 내용이 여기에 표시됩니다.',
    manualMode: 'Manual Mode',
    aiMode: 'AI Mode',
    userDetails: '사용자 정보',
    email: '이메일',
    phone: '핸드폰',
    region: '지역',
    carModel: '차종',
    carNumber: '차량번호',
    totalChats: '총 채팅 수',
    lastChat: '최근 채팅',
    quickActions: 'Quick Actions',
    exportChat: '채팅 내역 추출',
    addBlacklist: '블랙리스트 추가',
    chatHistory: 'Chat History',
    typeMessage: '메시지를 입력하세요...',
    darkMode: '다크모드',
    darkModeOn: '다크 테마 사용 중',
    darkModeOff: '라이트 테마 사용 중',
    language: '언어',
    totalUsers: '모든 테스트 개수',
    activeUsers: '이슈 발생율 평균',
    totalChats: '총 실행',
    chatsPerDay: '일간 평균 테스트 실행 수',
    usersByRegion: '지역별 테스트',
    usersByCarModel: '차종별 테스트',
    userInsights: '테스트 인사이트',
    quickControls: '빠른 제어',
    recentActivity: '최근 활동',
    newUser: '신규 사용자',
    returningUser: '재방문 사용자',
    sendAnnouncement: '공지 발송',
    toggleMaintenance: '점검 모드 전환',
    faqTop3: '자주 묻는 질문 TOP 3',
    userSatisfaction: '사용자 만족도',
    performanceMetrics: '성능 지표',
    responseTime: '평균 테스트 진행 시간',
    satisfaction: '7일간 이슈 감지율',
    serviceUptime: '안정적인 테스트 완료율'
  },
};

export const mockChats = [
  {
    id: 1,
    userName: 'Ahmad Rahman',
    userId: '#USER-234920-234',
    avatar: '/images/user-avatar.png',
    lastMessage: 'Saya ada masalah dengan kereta saya, boleh tolong?',
    timestamp: '2 min ago',
    isOnline: true,
    mode: 'ai',
    email: 'ahmad.rahman@email.com',
    phone: '+60123456789',
    region: 'Kuala Lumpur',
    carModel: 'Honda Civic',
    carNumber: 'ABC1234',
    totalChats: 23,
    lastChatDate: '2024-07-09'
  },
  {
    id: 2,
    userName: 'Siti Nurhaliza',
    userId: '#USER-345821-567',
    avatar: '/images/user-avatar1.png',
    lastMessage: 'Terima kasih atas bantuan anda.',
    timestamp: '5 min ago',
    isOnline: false,
    mode: 'manual',
    email: 'siti.nur@email.com',
    phone: '+60198765432',
    region: 'Penang',
    carModel: 'Toyota Vios',
    carNumber: 'DEF5678',
    totalChats: 15,
    lastChatDate: '2024-07-09'
  },
  {
    id: 3,
    userName: 'Raj Kumar',
    userId: '#USER-456732-890',
    avatar: '/images/user-avatar2.png',
    lastMessage: '로그인 테스트',
    timestamp: '10 min ago',
    isOnline: true,
    mode: 'ai',
    email: 'raj.kumar@email.com',
    phone: '+60167891234',
    region: 'Johor Bahru',
    carModel: 'Perodua Myvi',
    carNumber: 'GHI9012',
    totalChats: 8,
    lastChatDate: '2024-07-08'
  }
];

export const mockMessages = [
  { id: 1, sender: 'user', message: 'Saya ada masalah dengan kereta saya', timestamp: '10:30 AM', avatar: '/images/user-avatar.png' },
  { id: 2, sender: 'ai', message: 'Terima kasih telah menghubungi kami. Boleh ceritakan masalah apa yang anda hadapi?', timestamp: '10:31 AM' },
  { id: 3, sender: 'user', message: 'Kereta saya tidak boleh start pagi ini', timestamp: '10:32 AM', avatar: '/images/user-avatar.png' },
  { id: 4, sender: 'ai', message: 'Saya faham. Ada bunyi apa-apa ketika anda cuba start kereta?', timestamp: '10:33 AM' },
  { id: 5, sender: 'admin', message: 'Sila periksa bateri kereta anda.', timestamp: '10:35 AM', avatar: '/images/user-avatar4.png' }
];